# 2D Iteration

In this demonstration, you'll see how to iterate through a 2D array used nested loops, and we'll be using our iterative skills to locate trees in this world!

### Create the world

In [1]:
import numpy as np

# A 6x5 robot world
world = np.array([ [0, 0, 0, 1, 0],
                   [0, 0, 0, 1, 0],
                   [0, 1, 1, 0, 0],
                   [0, 0, 0, 0, 1],
                   [1, 0, 0, 1, 0],
                   [1, 0, 0, 0, 0] ])

# Print out some information about the world
print(world)
print('\nThe shape of this array is: ' + str(world.shape))

[[0 0 0 1 0]
 [0 0 0 1 0]
 [0 1 1 0 0]
 [0 0 0 0 1]
 [1 0 0 1 0]
 [1 0 0 0 0]]

The shape of this array is: (6, 5)


### Iterate through the items in the world

In [2]:
# This function uses nested for loops and knowledge
# about the shape of the array to print out each item with it's index
def iterate2D(world):
    # y-dimension (rows)
    for i in range(0, world.shape[0]):
        # x-dimension (columns)
        for j in range(0, world.shape[1]):
            print('Index ['+str(i)+']['+str(j)+'] = ' +str(world[i][j]))

# Call the iterate function
print('\n')
iterate2D(world)



Index [0][0] = 0
Index [0][1] = 0
Index [0][2] = 0
Index [0][3] = 1
Index [0][4] = 0
Index [1][0] = 0
Index [1][1] = 0
Index [1][2] = 0
Index [1][3] = 1
Index [1][4] = 0
Index [2][0] = 0
Index [2][1] = 1
Index [2][2] = 1
Index [2][3] = 0
Index [2][4] = 0
Index [3][0] = 0
Index [3][1] = 0
Index [3][2] = 0
Index [3][3] = 0
Index [3][4] = 1
Index [4][0] = 1
Index [4][1] = 0
Index [4][2] = 0
Index [4][3] = 1
Index [4][4] = 0
Index [5][0] = 1
Index [5][1] = 0
Index [5][2] = 0
Index [5][3] = 0
Index [5][4] = 0


### Find the first tree, `1`, in the world

In [3]:
# This function is similar to our iterate2D function,
# But looks for the first tree in the array and prints its location [x][y]
def first_tree(world):
    # iterates through all indices starting at the top-left [0][0]
    for i in range(0, world.shape[0]):
        for j in range(0, world.shape[1]):
            # check if a tree is found
            if(world[i][j] == 1):
                # if so, print the index and leave the loop with a return statement
                print('First tree found at location: ['+str(i)+']['+str(j)+']')
                return 

            
# Call the first_tree function
print('\n')
first_tree(world)



First tree found at location: [0][3]
